#!/usr/bin/env python3
"""Convert Scregg ROMs into the headers consumed by scregg.h.

Layouts and ROM order follow MAME src/mame/dataeast/btime.cpp (gfx_lnc).
Input: romszip/scregg_unpack. Output: source/src/machines/scregg.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROM_IN = ROOT / 'romszip' / 'scregg_unpack'
OUT_DIR = ROOT / 'source' / 'src' / 'machines' / 'scregg'

MAIN_FILES = ['scregg.e14', 'scregg.d14', 'scregg.c14', 'scregg.b14', 'scregg.a14']
GFX_FILES = ['scregg.j12', 'scregg.j10', 'scregg.h12', 'scregg.h10', 'scregg.g12', 'scregg.g10']
GENERATED = '// Auto-generated by romconv/scregg/convert_scregg.py - DO NOT EDIT\n'


def read_file(name: str, size: int) -> bytes:
    path = ROM_IN / name
    data = path.read_bytes()
    if len(data) != size:
        raise ValueError(f'{path}: expected {size} bytes, found {len(data)}')
    return data


def write_c_array(path: Path, name: str, data: bytes, comment: str):
    with path.open('w', newline='\n') as f:
        f.write(GENERATED + f'// {comment}\n')
        f.write(f'const unsigned char {name}[] = {{\n')
        for i in range(0, len(data), 16):
            f.write('  ' + ','.join(f'0x{b:02X}' for b in data[i:i+16]) + ',\n')
        f.write('};\n')


def decode_tiles(data: bytes, size: int):
    if len(data) != 0x6000 or size not in (8, 16):
        raise ValueError('Expected 0x6000 graphics bytes and 8x8 or 16x16 tiles')
    stride = size * size // 8
    tiles = []
    for code in range(0x2000 // stride):
        tile = []
        for y in range(size):
            row = []
            for x in range(size):
                # MAME sprites store the left 8 columns after the right 8.
                offset = code * stride + y
                if size == 16 and x < 8:
                    offset += 16
                bit = 7 - (x % 8)
                # Plane offsets 0x4000, 0x2000, 0 have weights 4, 2, 1.
                pen = sum(((data[plane * 0x2000 + offset] >> bit) & 1) << plane
                          for plane in range(3))
                row.append(pen)
            tile.append(row)
        # Match the portrait pre-rotation expected by scregg.cpp:
        # out[y][x] = native[size - 1 - x][y].
        tiles.append([[tile[size - 1 - x][y] for x in range(size)]
                      for y in range(size)])
    return tiles


def write_tiles(path: Path, name: str, tiles):
    size = len(tiles[0])
    with path.open('w', newline='\n') as f:
        f.write(GENERATED)
        f.write(f'const unsigned char {name}[{len(tiles)}][{size}][{size}] = {{\n')
        for tile in tiles:
            f.write('  {\n')
            for row in tile:
                f.write('    {' + ','.join(str(pen) for pen in row) + '},\n')
            f.write('  },\n')
        f.write('};\n')


def main():
    # Validate all required inputs before replacing any generated header.
    main_data = b''.join(read_file(name, 0x1000) for name in MAIN_FILES)
    gfx_data = b''.join(read_file(name, 0x1000) for name in GFX_FILES)
    color_data = read_file('screggco.c6', 0x20)
    chars = decode_tiles(gfx_data, 8)
    sprites = decode_tiles(gfx_data, 16)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    write_c_array(OUT_DIR / 'scregg_rom.h', 'scregg_rom', main_data,
                  'Main M6502 ROM mapped at 0x3000-0x7fff; last 0x1000 mirrored at 0xf000.')
    write_c_array(OUT_DIR / 'scregg_colorprom.h', 'scregg_colorprom', color_data,
                  '32-byte color PROM; hardware uses palette entries 0-7.')
    write_tiles(OUT_DIR / 'scregg_chartiles.h', 'scregg_chartiles', chars)
    write_tiles(OUT_DIR / 'scregg_spritetiles.h', 'scregg_spritetiles', sprites)
    print('Conversion complete. Headers written to', OUT_DIR)


if __name__ == '__main__':
    main()
