#!/usr/bin/env python3
"""
Simple ROM converter for Scregg.
Reads files from romszip/scregg_unpack and generates C header arrays
in src/machines/scregg/ named:
 - scregg_rom_main.h
 - scregg_chartiles.h
 - scregg_spritetiles.h
 - scregg_colorproms.h

This converter is intentionally conservative: it concatenates groups of
files into arrays in a common order; adjust the file order/constants if
you need to match exact MAME load offsets.
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root
ROM_IN = ROOT / 'romszip' / 'scregg_unpack'
OUT_DIR = ROOT / 'source' / 'src' / 'machines' / 'scregg'
OUT_DIR.mkdir(parents=True, exist_ok=True)

def read_file(p: Path) -> bytes:
    return p.read_bytes()

def write_c_array(path: Path, name: str, data: bytes, comment: str = ''):
    with open(path, 'w', newline='\n') as f:
        f.write(f"// Auto-generated by romconv/scregg/convert_scregg.py - DO NOT EDIT\n")
        if comment:
            f.write(f"// {comment}\n")
        f.write(f"const unsigned char {name}[] = {"{"}\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            line = ','.join(f'0x{b:02X}' for b in chunk)
            f.write('  ' + line + ',\n')
        f.write('};\n')

# Group files heuristically
main_files = ['scregg.a14','scregg.b14','scregg.c14','scregg.d14','scregg.e14']
gfx_files  = ['scregg.g10','scregg.g12','scregg.h10','scregg.h12','scregg.j10','scregg.j12']
color_files = ['screggco.b4','screggco.c6']

# Read and concat if present
main_data = b''
for fn in main_files:
    p = ROM_IN / fn
    if p.exists():
        main_data += read_file(p)

gfx_data = b''
for fn in gfx_files:
    p = ROM_IN / fn
    if p.exists():
        gfx_data += read_file(p)

color_data = b''
for fn in color_files:
    p = ROM_IN / fn
    if p.exists():
        color_data += read_file(p)

# Write out headers
if main_data:
    write_c_array(OUT_DIR / 'scregg_rom_main.h', 'scregg_rom_main', main_data, 'Scregg main CPU ROM (concatenated)')
else:
    print('No main ROM files found in', ROM_IN)

if gfx_data:
    write_c_array(OUT_DIR / 'scregg_chartiles.h', 'scregg_chartiles', gfx_data, 'Scregg graphics data (concatenated)')
    write_c_array(OUT_DIR / 'scregg_spritetiles.h', 'scregg_spritetiles', gfx_data, 'Scregg graphics data (duplicated for sprites)')

if color_data:
    write_c_array(OUT_DIR / 'scregg_colorproms.h', 'scregg_colorproms', color_data, 'Scregg color PROMs')

print('Conversion complete. Headers written to', OUT_DIR)
